server:  port: ${PORT:0}

spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/softwarece1/code#          uri: ${user.home}\\Desktop\\code
#          skip-ssl-validation: true